name: Python package

on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pytest tests --cov-report=xml --cov-report=html
      - name: Python Linter
        # You may pin to the exact commit or the version.
        # uses: sunnysid3up/python-linter@93076bd8f740f062069291d738fc70c1b4171c1d
        uses: sunnysid3up/python-linter@v0.1-beta.7
        with:
          # Source file or directory
          source: "main.py app"
          # Set strictness for lint [low, medium, high]
          strict: # optional, default is medium
          # Mypy options
          mypy-options: false # optional, default is 
          # Pylint options
          pylint-options: --rcfile=.pylintrc
          # Black options
          black-options: false # optional, default is 
          # Isort options
          isort-options: false # optional, default is 
          # Confirm if source is a Django project
          django: false # optional
